spring:
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://products
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=2
#            - name: SampleCookie
#              args:
#                cookieName: myCookie
#                value: myValue
#                message: Mensaje personalizado para productos
        - id: items
          uri: lb://items/
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
